#!/usr/bin/env node
'use strict';
// Parse World_Cup_2026_Schedule.md into a structured matches.js module.
// Each match: { etDate, etTime, cetTime, cetDate, match, home, away, group, venue, isGermany }
// cetDate = the calendar date the match AIRS in Germany (Europe/Berlin). A CET cell
// like "4:00 AM (Jun 12)" airs on Jun 12; a plain "9:00 PM" airs on the section date.
const fs = require('node:fs');
const path = require('node:path');

const MONTHS = { Jan:1, Feb:2, Mar:3, Apr:4, May:5, Jun:6, Jul:7, Aug:8, Sep:9, Oct:10, Nov:11, Dec:12 };
const YEAR = 2026;

function iso(month, day) {
  return `${YEAR}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

// Heading like "### Thursday, Jun 11" -> { iso, weekday }
function parseHeading(line) {
  const m = line.match(/^###\s+(\w+),\s+(\w+)\s+(\d+)/);
  if (!m) return null;
  return { weekday: m[1], iso: iso(MONTHS[m[2]], Number(m[3])) };
}

// Round headings like "## Group Stage", "## Round of 32", etc.
function parseRound(line) {
  const m = line.match(/^##\s+(?!#)(.+)$/);
  return m ? m[1].trim() : null;
}

function parse(mdPath) {
  const text = fs.readFileSync(mdPath, 'utf8');
  const lines = text.split('\n');
  const matches = [];
  let curDate = null;       // { iso, weekday } from ### heading
  let curRound = 'Group Stage';

  for (const raw of lines) {
    const line = raw.trim();
    const round = parseRound(raw);
    if (round && !raw.startsWith('###')) { curRound = round; continue; }
    const h = parseHeading(raw);
    if (h) { curDate = h; continue; }
    // table data rows: | ET | CET | Match | Group/Round | Venue |
    if (!line.startsWith('|')) continue;
    if (/^\|\s*ET\s*\|/.test(line)) continue;            // header row
    if (/^\|\s*-+/.test(line.replace(/\s/g, ''))) continue; // separator
    const cells = line.split('|').slice(1, -1).map((c) => c.trim());
    if (cells.length < 5) continue;
    const [etTime, cetRaw, matchStr, groupRound, venue] = cells;
    if (!/ v /.test(matchStr)) continue;
    if (!curDate) throw new Error('match row before any date heading: ' + line);

    // CET cell: "9:00 PM" (same day) OR "4:00 AM (Jun 12)" (spills to next day)
    let cetTime = cetRaw;
    let cetDate = curDate.iso;
    const spill = cetRaw.match(/^(.+?)\s*\((\w+)\s+(\d+)\)\s*$/);
    if (spill) {
      cetTime = spill[1].trim();
      cetDate = iso(MONTHS[spill[2]], Number(spill[3]));
    }

    const [home, away] = matchStr.split(' v ').map((s) => s.trim());
    const isGermany = /(^|\b)Germany(\b|$)/.test(home) || /(^|\b)Germany(\b|$)/.test(away);

    matches.push({
      etDate: curDate.iso,
      etTime,
      cetTime,
      cetDate,
      weekday: curDate.weekday,
      match: matchStr,
      home,
      away,
      group: groupRound,
      round: curRound,
      venue,
      isGermany,
    });
  }
  return matches;
}

function main() {
  const src = path.join(__dirname, 'World_Cup_2026_Schedule.md');
  const matches = parse(src);
  const banner = '// AUTO-GENERATED by cup/parse.js from World_Cup_2026_Schedule.md — do not edit by hand.\n';
  const body = "'use strict';\nmodule.exports = " + JSON.stringify(matches, null, 2) + ';\n';
  const out = path.join(__dirname, 'matches.js');
  fs.writeFileSync(out, banner + body);
  console.log(`Parsed ${matches.length} matches -> ${out}`);
}

if (require.main === module) main();
module.exports = { parse };
