'use strict';
// Backstory pages for Berlin sights — history + fun background, one page per sight.
// Rendered by render.renderStoryPage() into /trips/2026/germany/berlin/<slug>/.
// Each story: slug, emoji, title, teaser (card text), day (ISO of the trip day it
// belongs to), where (one-liner), maps (Google Maps query), sections (h + html),
// facts (bullets for the "Did you know?" box).

const stories = [
  {
    slug: 'brandenburger-tor',
    emoji: '🏛️',
    title: 'Brandenburg Gate',
    teaser: 'Napoleon stole its statue, the Wall trapped it in no-man’s-land, and Reagan stood here demanding it be opened.',
    day: '2026-07-07',
    where: 'Pariser Platz — western end of Unter den Linden',
    maps: 'Brandenburger Tor Pariser Platz Berlin',
    sections: [
      { h: 'A city gate that became a symbol', html: '<p>Built 1788–1791 as the grandest of Berlin’s eighteen city gates, modelled on the entrance to the Acropolis in Athens. On top: the Quadriga — a four-horse chariot driven by the goddess of victory. It was meant to be a gate of peace. History had other plans.</p>' },
      { h: 'Napoleon steals the horses', html: '<p>In 1806 Napoleon beat Prussia, marched through this gate, and liked the Quadriga so much he had it taken apart and shipped to Paris in crates. Berliners mockingly called him &ldquo;the horse thief of Berlin&rdquo;. Eight years later Prussian troops took Paris and brought the horses home — and the goddess got a new accessory: the Iron Cross on her staff, designed by Karl Friedrich Schinkel.</p>' },
      { h: 'Twenty-eight years in no-man’s-land', html: '<p>When the Wall went up in 1961, the Gate ended up inside the border strip — in East Berlin, but sealed off from East Berliners too. For 28 years nobody could walk through it. West Berliners climbed viewing platforms to look at it across the Wall; East Berlin guards patrolled around it. In June 1987 US President Ronald Reagan stood on the western side and said the famous words: <em>&ldquo;Mr. Gorbachev, tear down this wall!&rdquo;</em></p>' },
      { h: 'The party of the century', html: '<p>On 22 December 1989, six weeks after the Wall fell, the crossing at the Gate was opened while a hundred thousand people cheered in the rain. Ever since, this is where Berlin celebrates everything — New Year’s Eve, World Cup wins, marathon finishes. When you stand under it at sunset, you’re standing on the old death strip.</p>' },
    ],
    facts: [
      'The Gate survived WWII, but barely — look for the shrapnel scars on the columns.',
      'The Quadriga faces east, into the city — Napoleon supposedly wanted it facing Paris.',
      'The room inside the north wing is an official &ldquo;Room of Silence&rdquo; — anyone may sit quietly there.',
      'Pariser Platz was called &ldquo;the empty square&rdquo; during the Cold War: every building around it was rubble or razed.',
    ],
  },
  {
    slug: 'reichstag',
    emoji: '🏛',
    title: 'Reichstag & the glass dome',
    teaser: 'Burned in 1933, stormed in 1945, wrapped in fabric in 1995 — now you walk on glass above the parliament.',
    day: '2026-07-09',
    where: 'Platz der Republik 1 — next to the Brandenburg Gate',
    maps: 'Reichstag Platz der Republik 1 Berlin',
    sections: [
      { h: 'A parliament with scars', html: '<p>Finished in 1894 for the German Empire’s parliament. The inscription <em>&ldquo;Dem Deutschen Volke&rdquo;</em> — &ldquo;To the German People&rdquo; — was only added in 1916, cast from two French cannons captured in the Napoleonic Wars. In February 1933 the building burned in a mysterious fire; the Nazis used it within 24 hours as the excuse to suspend civil rights and arrest the opposition. The Reichstag never housed a free parliament under Hitler.</p>' },
      { h: '1945: the photo that ended the war', html: '<p>For the Red Army the Reichstag was the symbolic target in the Battle of Berlin. The photo of a Soviet soldier raising the red flag on its roof in May 1945 became one of the most famous pictures of the 20th century. Inside, Soviet soldiers wrote their names and messages on the walls in Cyrillic — and here’s the thing: <strong>the graffiti is still there.</strong> The architects preserved whole walls of it. Look for it as you go up.</p>' },
      { h: 'Wrapped, rebuilt, reopened', html: '<p>After decades on the edge of West Berlin — the Wall ran metres behind it — the building got the strangest rebirth imaginable: in summer 1995 the artists Christo and Jeanne-Claude wrapped the entire Reichstag in silver fabric for two weeks. Five million people came. Then Sir Norman Foster gutted it and crowned it with the glass dome. Since 1999 it’s the seat of the Bundestag, the German parliament.</p>' },
      { h: 'Why the dome matters', html: '<p>The dome isn’t decoration — it’s an argument. Citizens walk on a spiral ramp <em>above</em> the plenary chamber, literally over the heads of their representatives: the people above the parliament. The mirrored cone in the middle funnels daylight down into the chamber. At sunset the whole city glows at your feet — free of charge, by design.</p>' },
    ],
    facts: [
      'Booking is free but mandatory — every visitor is name-checked against a passport at airport-style security.',
      'The dome is open until midnight (last entry 21:45) — the night views beat the daytime ones.',
      'A wild-boar-proof fact for the drive: the dome weighs 1,200 tonnes and its mirror cone carries 360 mirrors.',
      'The preserved Soviet graffiti includes names, hometowns and a few lines best left untranslated.',
    ],
  },
  {
    slug: 'berliner-mauer',
    emoji: '🧱',
    title: 'The Berlin Wall',
    teaser: 'Built overnight in 1961, it cut a city in half for 28 years — and fell because of a bungled press conference.',
    day: '2026-07-08',
    where: 'Wall Memorial: Bernauer Straße 111 (S Nordbahnhof)',
    maps: 'Gedenkstaette Berliner Mauer Bernauer Strasse 111',
    sections: [
      { h: 'Why a country walled its people in', html: '<p>By 1961, around 3.5 million East Germans — roughly one in six — had left for the West, most of them simply by walking into West Berlin. The DDR was bleeding doctors, engineers and entire graduating classes. In the night of 12–13 August 1961, soldiers rolled out barbed wire around all of West Berlin. Within weeks the wire became concrete. Officially it was the &ldquo;Anti-Fascist Protection Rampart&rdquo;. Nobody was ever fooled: every gun on it pointed inward.</p>' },
      { h: 'Bernauer Straße — the street of jumps', html: '<p>Here the border ran along the house fronts: the buildings were East, the pavement was West. In the first days people escaped through windows — firefighters from the West held out jumping sheets while DDR police hammered the doors. Ida Siekmann, who jumped from her third-floor window on 22 August 1961, was the Wall’s first casualty. Days earlier, 19-year-old border guard Conrad Schumann leapt over the barbed wire here mid-patrol — the photo <em>&ldquo;Leap into Freedom&rdquo;</em> went around the world. Later the houses were emptied and demolished; only the bricked-up facades remained.</p>' },
      { h: 'The death strip', html: '<p>What people call &ldquo;the Wall&rdquo; was really two walls with a floodlit corridor between them: raked sand (to show footprints), signal fences, dog runs, watchtowers, and guards with shoot-to-kill orders. At least 140 people died at the Berlin Wall. The memorial here preserves the last complete stretch — death strip, tower and all. In October 1964 students dug &ldquo;Tunnel 57&rdquo; from a bakery on this street, 12 metres down — 57 people crawled to the West in two nights, the biggest tunnel escape of them all.</p>' },
      { h: 'The press conference that ended it', html: '<p>On 9 November 1989, with the DDR crumbling, spokesman Günter Schabowski was handed a note about new travel rules minutes before a live press conference. Asked when they took effect, he shuffled his papers and guessed: <em>&ldquo;As far as I know… immediately, without delay.&rdquo;</em> It wasn’t supposed to be. Tens of thousands marched to the crossings; just before midnight the overwhelmed guards at Bornholmer Straße gave up and opened the gate. The Wall had stood 10,316 days. People danced on it by morning.</p>' },
    ],
    facts: [
      'Total length around West Berlin: 155 km — only 43 km of it ran through the middle of the city.',
      'Over 5,000 people still made it across — by tunnel, homemade hot-air balloon, zipline, and one stolen tank.',
      'The M10 tram you’ll ride follows the old border strip for much of its route.',
      'Twin rows of cobblestones across streets and pavements mark where the Wall stood — you’ll cross them all week without noticing unless you look.',
    ],
  },
  {
    slug: 'checkpoint-charlie',
    emoji: '🪖',
    title: 'Checkpoint Charlie',
    teaser: 'US and Soviet tanks faced off here at 100 metres — and a man once drove under the barrier in a car with the windshield removed.',
    day: '2026-07-09',
    where: 'Friedrichstraße 43–45 (U6 Kochstraße)',
    maps: 'Checkpoint Charlie Friedrichstrasse Berlin',
    sections: [
      { h: 'Why &ldquo;Charlie&rdquo;?', html: '<p>Nothing to do with anyone named Charlie — it’s the NATO phonetic alphabet. Checkpoint Alpha was the autobahn crossing at Helmstedt, Bravo the entry into West Berlin at Dreilinden, and this one — the only crossing where foreigners and Allied personnel could pass between the sectors — was the third: Charlie. The famous sign says it in four languages: <em>&ldquo;You are leaving the American sector.&rdquo;</em></p>' },
      { h: 'October 1961: tanks, 16 hours, 100 metres', html: '<p>Two months after the Wall went up, a US diplomat was stopped by DDR guards on his way to the opera in East Berlin — a violation of the four-power agreement that Allied personnel moved freely. The US responded by escorting civilians through with armed jeeps. Then someone escalated: ten American M48 tanks rolled up to the checkpoint. Ten Soviet T-55s met them, engines running, live ammunition loaded, facing each other across about 100 metres. For sixteen hours the Cold War was one nervous lieutenant away from going hot, until Kennedy and Khrushchev quietly agreed to pull back one tank at a time — Soviets first, by five metres, then the Americans.</p>' },
      { h: 'The escape artists', html: '<p>Because Charlie was a vehicle crossing, it attracted the most creative escapes. The best one: in 1963 Austrian Heinz Meixner rented an Austin-Healey Sprite, a sports car so low that with the windshield removed it fit <em>under</em> the barrier — he hit the gas with his East German girlfriend beside him and her mother in the trunk. It worked. Twice more, until the DDR welded bars under the barrier. Others came through in hollowed-out cable drums, two suitcases joined together, and a modified Isetta bubble car with the heater removed.</p>' },
      { h: 'What you see today', html: '<p>The guardhouse is a replica (the original is in the Allied Museum), the &ldquo;soldiers&rdquo; are actors, and the surroundings are pure tourist circus — but the free open-air panels along Friedrichstraße tell the real stories well. For the real chill, step into the asisi Panorama next door: a 1:1 view over the Wall from a Kreuzberg rooftop on an ordinary 1980s day. That grey emptiness is what all the fuss was about.</p>' },
    ],
    facts: [
      'The checkpoint hut was left deliberately shabby — the Allies refused to build anything permanent, to avoid recognising the border.',
      'During the 1961 standoff, both sides’ tanks had orders to fire if fired upon — decision time: seconds.',
      'The McDonald’s overlooking the site occupies what was once the most surveilled corner in Europe.',
      'Movie fans: this is the checkpoint in every Cold War film from James Bond (&ldquo;Octopussy&rdquo;) to &ldquo;Bridge of Spies&rdquo;.',
    ],
  },
  {
    slug: 'east-side-gallery',
    emoji: '🎨',
    title: 'East Side Gallery',
    teaser: 'The longest surviving stretch of Wall — 1.3 km painted by 118 artists in 1990, including THAT kiss.',
    day: '2026-07-09',
    where: 'Mühlenstraße, along the Spree (U/S Warschauer Straße)',
    maps: 'East Side Gallery Muehlenstrasse Berlin',
    sections: [
      { h: 'Paint where guns used to point', html: '<p>In spring 1990 — Wall open, DDR still technically existing — 118 artists from 21 countries were invited to paint the <em>eastern</em> side of a 1.3 km stretch along the Spree. That side had always been blank concrete: no East Berliner could ever get close enough to touch it, let alone paint it. Covering it in colour was the point. It opened in September 1990 as the East Side Gallery and became the longest open-air gallery in the world.</p>' },
      { h: 'The kiss everyone photographs', html: '<p>Dmitri Vrubel’s <em>&ldquo;My God, Help Me to Survive This Deadly Love&rdquo;</em> shows Soviet leader Leonid Brezhnev and DDR leader Erich Honecker kissing on the mouth. It’s based on a real photo from 1979 — the &ldquo;socialist fraternal kiss&rdquo; was an actual diplomatic ritual between communist leaders, and Brezhnev was famously enthusiastic about it. The painting turned the ritual into the defining image of a suffocating alliance.</p>' },
      { h: 'The Trabi breaking through', html: '<p>A few panels along, Birgit Kinder’s <em>&ldquo;Test the Best&rdquo;</em> shows a Trabant — the DDR’s cardboard-bodied people’s car — smashing through the Wall, licence plate reading NOV 9-89, the night it fell. Between the murals, look at the river: people drowned trying to swim this stretch of the Spree, because the whole width of the water belonged to the East.</p>' },
    ],
    facts: [
      'Heritage-protected since 1991 — the murals were fully repainted by the original artists in 2009.',
      'The Oberbaumbrücke next door was a pedestrian-only border crossing; today the U1 rattles over its brick towers.',
      'Kinder’s Trabi and Vrubel’s kiss are among the most photographed artworks in Germany.',
      'The back (west-facing) side was the graffiti side during the Wall years — West Berliners could walk right up to it.',
    ],
  },
  {
    slug: 'karl-marx-allee',
    emoji: '🚩',
    title: 'Karl-Marx-Allee',
    teaser: 'Stalin’s showcase boulevard — &ldquo;workers’ palaces&rdquo; in wedding-cake style, and the street where the 1953 uprising began.',
    day: '2026-07-08',
    where: 'Between Alexanderplatz and Frankfurter Tor (U5)',
    maps: 'Karl-Marx-Allee Strausberger Platz Berlin',
    sections: [
      { h: 'Palaces for the proletariat', html: '<p>Built from 1952 on the rubble of bombed-out Friedrichshain, and originally named <strong>Stalinallee</strong>, this was the DDR’s showcase project: a 90-metre-wide, two-kilometre boulevard of monumental apartment blocks in Moscow’s &ldquo;wedding-cake&rdquo; style. The official line: palaces for workers, not villas for the rich — with lifts, central heating and tiled facades at a time when much of Berlin still lived in ruins. Locals noticed the tiles kept falling off and joked about &ldquo;Stalin’s bathroom&rdquo;.</p>' },
      { h: 'June 1953: the builders revolt', html: '<p>Ironically, the workers building the workers’ palaces lit the fuse of the DDR’s first uprising. On 16 June 1953, construction crews on this street downed tools over raised work quotas and marched on the government quarter. By the next day strikes and protests had spread to hundreds of towns across the DDR — and were crushed by Soviet tanks. Dozens were killed. 17 June became West Germany’s national holiday for decades; the street of that name runs from the Brandenburg Gate.</p>' },
      { h: 'De-Stalinised overnight', html: '<p>In 1961, as Moscow disowned Stalin, the street was quietly renamed Karl-Marx-Allee — and the 4.8-metre bronze Stalin statue vanished in a single night, melted down; even the street signs were swapped before morning. Walk it today for the full effect: Strausberger Platz’s fountain circle, the twin domed towers at Frankfurter Tor, and <strong>Kino International</strong>, the DDR’s premiere cinema, where East Berlin’s film stars walked a socialist red carpet. On 4 November 1989, five days before the Wall fell, half a million people marched down this street demanding change.</p>' },
    ],
    facts: [
      'The boulevard was built partly with &ldquo;rubble women&rdquo; clearing 40 million cubic metres of wartime debris.',
      'Apartments here were assigned as rewards — activists, model workers, loyal artists.',
      'Kino International still runs films nightly; the auditorium is original 1963.',
      'Architecture nerds pilgrimage here: it’s the longest architectural monument in Europe.',
    ],
  },
  {
    slug: 'ddr-alltag',
    emoji: '🚗',
    title: 'Everyday life in the DDR',
    teaser: 'Ten-year waiting lists for a cardboard car, one informer per ninety citizens, and the little traffic-light man who survived it all.',
    day: '2026-07-08',
    where: 'DDR Museum, Karl-Liebknecht-Str. 1 (opposite the Dom)',
    maps: 'DDR Museum Berlin Karl-Liebknecht-Strasse 1',
    sections: [
      { h: 'The Trabi: 26 horsepower of patience', html: '<p>The Trabant’s body was Duroplast — resin reinforced with cotton waste — because steel was scarce. Two-stroke engine, 26 hp, blue exhaust smoke you could smell a block away. The punchline: you waited <strong>ten to fifteen years</strong> for one. People ordered a Trabi for their kids when they were born. When the Wall fell, columns of Trabis sputtering into West Berlin became the image of the reunification — which is why one is painted breaking through the East Side Gallery.</p>' },
      { h: 'The Stasi: a country listening to itself', html: '<p>The Ministry for State Security employed around 91,000 people full-time — plus roughly 189,000 &ldquo;unofficial collaborators&rdquo;: neighbours, colleagues, sometimes friends and family, filing reports. That’s about one informer for every ninety citizens, the densest surveillance network in history. Files stacked end to end would run over 100 km. At the DDR Museum you can sit in a bugged living room and play back what the microphones heard.</p>' },
      { h: 'Growing up East', html: '<p>School came with a blue neckerchief: the Young Pioneers, then the FDJ youth organisation — camping trips, parades, and politics baked into everything. Jeans were suspicious, Western radio was forbidden-but-everyone-listened, and a package from West German relatives (real coffee! chocolate!) was a family event. Bananas were so rare that the banana queue became the DDR’s own national joke.</p>' },
      { h: 'The Ampelmännchen wins in the end', html: '<p>The jaunty hat-wearing traffic-light man was designed in 1961 by East German traffic psychologist Karl Peglau, who argued a friendly, chunky figure was easier to see and obey. After reunification the West started swapping him out — and Berliners revolted. The &ldquo;Save the Ampelmännchen&rdquo; campaign won: today he’s spread to crossings in the western half too. The DDR’s most beloved export conquered Berlin twice.</p>' },
    ],
    facts: [
      'DDR slang for the Trabant: &ldquo;Rennpappe&rdquo; — racing cardboard.',
      'The DDR Museum’s Trabi simulator lets you drive a virtual Plattenbau district — kids first.',
      'Intershops sold Western goods for Western money — most East Germans could only smell the coffee at the door.',
      'The DDR had full employment, but you could be jailed for &ldquo;asocial behaviour&rdquo; if you refused to work.',
    ],
  },
  {
    slug: 'treptower-ehrenmal',
    emoji: '⭐',
    title: 'Soviet War Memorial Treptow',
    teaser: 'Seven thousand Red Army soldiers are buried under Germany’s largest Soviet memorial — crowned by a 12-metre soldier carrying a child.',
    day: '2026-07-09',
    where: 'Treptower Park, Puschkinallee (S Treptower Park)',
    maps: 'Sowjetisches Ehrenmal Treptower Park Berlin',
    sections: [
      { h: 'A cemetery disguised as a triumph', html: '<p>Around 80,000 Red Army soldiers died taking Berlin in the last three weeks of the war in Europe. About 7,000 of them are buried here, under what became the largest Soviet war memorial in Germany, opened on 8 May 1949 — four years to the day after the surrender. This isn’t just a monument; it’s a military cemetery, which is why the scale is designed to make you fall silent: a 100,000-square-metre axis of weeping birches, granite banners and stone sarcophagi.</p>' },
      { h: 'The soldier with the child', html: '<p>The 12-metre bronze at the far end shows a Soviet soldier with a sword lowered onto a shattered swastika, carrying a rescued German girl. The official inspiration: Sergeant Nikolai Masalov, who — the story goes — crossed open ground under fire during the battle to pull a crying German toddler from the crossfire near the Landwehr Canal. Sculptor Yevgeny Vuchetich later built the even larger &ldquo;Motherland Calls&rdquo; in Volgograd; this one, people say, he considered the more human of the two.</p>' },
      { h: 'Granite with a dark past', html: '<p>The red granite cladding the banners is widely reported to have come from Hitler’s demolished New Reich Chancellery — the Soviets tore the building down and, so the account goes, recycled the Führer’s marble into his defeat. The sixteen stone sarcophagi along the axis stand for the sixteen Soviet republics, carved with battle reliefs and quotes from Stalin in Russian and German — one of the few places in Germany where Stalin’s words still stand in stone.</p>' },
    ],
    facts: [
      'By treaty, reunified Germany is obliged to maintain Soviet memorials — gardeners tend this one year-round.',
      'The kneeling soldiers at the entrance frame the axis so the statue appears exactly between them — stand on the centre line.',
      'Every 8–9 May, thousands lay flowers here for the end-of-war anniversary.',
      'It’s the most monumentally &ldquo;Soviet&rdquo; place in Berlin — more so than anything on Karl-Marx-Allee.',
    ],
  },
  {
    slug: 'holocaust-mahnmal',
    emoji: '🕯️',
    title: 'Memorial to the Murdered Jews of Europe',
    teaser: '2,711 concrete blocks with no inscription, no names, no fixed meaning — built to make you feel lost on purpose.',
    day: '2026-07-07',
    where: 'Cora-Berliner-Straße 1 — one block south of the Brandenburg Gate',
    maps: 'Holocaust Mahnmal Cora-Berliner-Strasse Berlin',
    sections: [
      { h: 'A field you walk into', html: '<p>One block from the Brandenburg Gate, 2,711 grey concrete stelae cover a full city block — same footprint, different heights, on ground that dips and rolls. Architect Peter Eisenman refused to explain what it means. There’s no entrance, no path, no plaque telling you what to feel. You just walk in — and somewhere near the middle, where the blocks tower over your head and the city noise drops away, it works on you: disorientation, loneliness, unease. That’s the design.</p>' },
      { h: 'Six million names below', html: '<p>Under the field, the <strong>Ort der Information</strong> does what the stelae refuse to do: it gives the victims back their names and faces. One room reads out names and short biographies — reading all of them aloud would take almost seven years. It opened in 2005, after seventeen years of national debate about whether Germany could — or should — build a central memorial to its own greatest crime in the middle of its capital.</p>' },
      { h: 'How to visit it', html: '<p>Walk the field slowly and let it do its thing — and please, no climbing or posing on the blocks; it’s a memorial, not a photo prop, and Berliners will say so. It’s open 24/7 and takes fifteen quiet minutes on the way from Potsdamer Platz to the Gate — which is exactly the route we’re walking on arrival evening.</p>' },
    ],
    facts: [
      'The number 2,711 has no official meaning — Eisenman said even that is deliberate.',
      'The blocks are coated against graffiti; the coating company’s WWII history itself became a national controversy.',
      'Memorials to Sinti and Roma, and to persecuted homosexuals, stand just across the street in the Tiergarten.',
      'At the field’s deepest point the stelae are over 4 metres tall.',
    ],
  },
  {
    slug: 'berlin-food',
    emoji: '🌭',
    title: 'Berlin on a plate',
    teaser: 'Currywurst was invented with bartered ketchup in 1949; the Döner kebab as we know it was born at Bahnhof Zoo in 1972.',
    day: '2026-07-08',
    where: 'Konnopke’s (Prenzlauer Berg) · Curry 36 & Mustafa’s (Mehringdamm) · Rüyam (Schöneberg)',
    maps: 'Konnopkes Imbiss Schoenhauser Allee Berlin',
    sections: [
      { h: 'Currywurst: born from the black market', html: '<p>On 4 September 1949, in bombed-out Charlottenburg, kiosk owner <strong>Herta Heuwer</strong> was bored and low on stock. She’d bartered with British soldiers for ketchup, Worcestershire sauce and curry powder, mixed them hot, and poured the result over a chopped fried sausage. Berlin’s national dish was born. She later patented her sauce as &ldquo;Chillup&rdquo; and at its peak her stand sold 10,000 portions a week. Berlin eats roughly 70 million Currywürste a year.</p>' },
      { h: 'East wurst vs West wurst', html: '<p>Currywurst split with the city. In the East, casings were scarce — so <strong>Konnopke’s</strong>, the family stand under the U2 viaduct since 1930, made it <em>ohne Darm</em>: skinless, softer, sauce from a recipe still kept secret. It was the first Currywurst in East Berlin (1960) and survived the DDR as a family business — a small miracle in a nationalised economy. In the West, <strong>Curry 36</strong> on Mehringdamm serves the crisp-skinned version to a permanent crowd. Eat both, pick a side: it’s a legitimate Berlin argument.</p>' },
      { h: 'The Döner is a Berliner', html: '<p>Rotating spit meat is Turkish; the <em>sandwich</em> is Berlin. The most-told origin story: in 1972, Turkish guest worker <strong>Kadir Nurman</strong> set up a stand at Bahnhof Zoo and put the meat into bread with salad, so West Berliners could eat it on the move. Today Berlin has more kebab shops than Istanbul and the Döner outsells every burger chain in the city combined. The queue at Mustafa’s runs to an hour; Rüyam in Schöneberg — ten minutes from our hotel — is the connoisseurs’ shortcut.</p>' },
      { h: 'The Pfannkuchen problem', html: '<p>The jam-filled doughnut the rest of Germany calls a &ldquo;Berliner&rdquo; is called <strong>Pfannkuchen</strong> in Berlin — order a &ldquo;Berliner&rdquo; here and the baker knows you’re a tourist. Round out the list with Buletten (Berlin’s meatballs, a word from the French Huguenots), Königsberger Klopse in caper sauce, and — for the grown-ups — a Berliner Weisse mit Schuss: sour wheat beer dyed red with raspberry or green with woodruff syrup.</p>' },
    ],
    facts: [
      'Herta Heuwer’s kiosk site at Kantstr. 101 has a memorial plaque — probably the only one ever dedicated to a sauce.',
      'The Volkswagen factory canteen makes its own Currywurst with a VW part number: 199 398 500 A.',
      'Street Food Thursday at Markthalle Neun (17–22) revived a 19th-century market hall that survived war, DDR and a supermarket takeover.',
      '&ldquo;Späti&rdquo; = Berlin’s late-night corner shops; sitting outside one with a bottle is a protected local ritual.',
    ],
  },
  {
    slug: 'kadewe',
    emoji: '🛍️',
    title: 'KaDeWe & West Berlin glamour',
    teaser: 'The department store that became capitalism’s shop window — East Berliners’ first stop when the Wall fell.',
    day: '2026-07-07',
    where: 'Tauentzienstraße 21–24 (U Wittenbergplatz) — 8 min walk from the hotel',
    maps: 'KaDeWe Tauentzienstrasse Berlin',
    sections: [
      { h: 'The biggest shop on the continent', html: '<p>Kaufhaus des Westens — &ldquo;Department Store of the West&rdquo; — opened in 1907 and grew into continental Europe’s largest department store: 60,000 m², eight floors. The name became literal after 1961: for West Berlin, a walled island inside the DDR, KaDeWe was the glittering proof that the island lifestyle worked. Every subsidised West Berliner luxury the East couldn’t have was stacked here eight storeys high, twenty minutes’ walk from the death strip.</p>' },
      { h: 'November 1989: the pilgrimage', html: '<p>When the Wall opened, East Berliners with their 100 Deutschmarks of &ldquo;welcome money&rdquo; streamed across the city — and famously, one of the first places they went was KaDeWe, just to look. News footage from those days shows crowds simply standing in the food halls, staring. The sixth-floor <strong>Feinschmecker-Etage</strong> — the legendary gourmet floor with its oyster bars and a wall of chocolates — is still the show-stopper. Go hungry, leave broke.</p>' },
      { h: 'Wittenbergplatz: the pretty U-Bahn station', html: '<p>The station in front (1913) is a listed jewel with its original wooden ticket hall. By the exit, note the dark memorial board listing concentration camps — &ldquo;Places of terror that we should never forget&rdquo; — placed where West Berlin’s shopping mile begins. Very Berlin: glamour and memory on the same square.</p>' },
    ],
    facts: [
      'KaDeWe’s food floor stocks around 34,000 products — including a chocolate counter longer than a tram.',
      'The store was destroyed in 1943 when a US bomber crashed into it; the 1950 reopening was celebrated as West Berlin’s comeback.',
      'David Bowie and Iggy Pop, living in Schöneberg in the late 70s, shopped here — your hotel sits in their old neighbourhood.',
      'Wittenbergplatz to Nollendorfplatz is one stop on the U-Bahn — or a 7-minute walk past the Ampelmann shop windows.',
    ],
  },
];

module.exports = { stories, bySlug: Object.fromEntries(stories.map((s) => [s.slug, s])) };
